name: smarttracker_assignment03
description: "SmartTracker - Riphah University CS4723 Assignment #3"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.2

  # Maps & Location
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1

  # Camera & Image
  camera: ^0.11.0+1
  image_picker: ^1.1.2

  # Network
  http: ^1.2.2
  connectivity_plus: ^6.0.5

  # Local Storage (Offline - Last 5 activities)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4

  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Optional: Add app icon or assets later
  # assets:
  #   - assets/images/